### ISSUE TITLE
Tokio runtime crash

### ISSUE THREAD

**Issue by ademar111190** [breez/breez-sdk#283]
I just got the following crash, the app was open but I was not doing anything in particular:

```
08:18:16.983 11431-11644 libc                                 A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 11644 (tokio-runtime-w), pid 11431 (m.cBreez.client)
```

The logs: [c-breez.logs.zip](https://github.com/breez/breez-sdk/files/11893766/c-breez.logs.zip)

**Comment by roeierez** [comment]
Can you share more logs? Last time I checked this morning the online build as running fine.
Is it your own build?

**Comment by roeierez** [comment]
I reproduced it myself on an old node and it seems that the signer is crashing:

`06-29 06:47:25.504  5972  5972 F DEBUG   : Abort message: 'called `Result::unwrap()` on an `Err` value: Unknown URI /cln.Node/ListClosedChannels, can't decode payload'`

Talked to @cdecker and it seems that this method is only available on an advanced version node and when running the signer there is an attempt to upgrade the node which fails because it is already scheduled.
The right thing to do is to wait for the node to be upgraded before scheduling but currently we don't have a way to do that in greenlight. Opened an issue : https://github.com/Blockstream/greenlight/issues/193
On the next schedule it is likely that the node upgrade will be done, this is the reason you only reproduced it once.

**Comment by ademar111190** [comment]
Thanks for diving on it @roeierez 🙏

**Comment by ademar111190** [comment]
I'm closing this issue as they fixed it on greenlight.
