### ISSUE TITLE
bolt11 in event `INVOICE_PAID` event is not correct

### ISSUE THREAD

**Issue by callebtc** [breez/breez-sdk#399]
1) Create invoice with `bolt11_a, payment_hash_a`
2) Pay that invoice from any other wallet
3) Receive `INVOICE_PAID` with `bolt11_b, payment_hash_b` and notice that `bolt11_a != bolt11_b` but `payment_hash_a == payment_hash_b`

Seems like something is changing the invoice retroactively? But still signing it correctly.

Two examples

1. The one I create: https://lightningdecoder.com/lnbc10n1pjwvrntdq2f38xy6t5wvpp50udjtr576fjgm3drvt5zhqwax7ap3c4h3ehmwug9cmngdpwy8l9qxqyjw5qsp58s0yxg6szwhfxeg5s3kxvkt9eaaugejtdzpttsef5qwxg06evegs9qrsgqcqpxrzjqtypret4hcklglvtfrdt85l3exc0dctdp4qttmtcy5es3lpt6uts6s0yarww0ua5wyqqqqlgqqqqqzsqygqv750vuv5zn734feczlf95t4v8sdzyjj67lzvwypjr627vcj9zypddk5yyawyahztvgfh6dxt9kg8zxfn42w4kjqlp0sc9l764d24aqpwzdh5s

2. The one I get from the event listener: https://lightningdecoder.com/lnbc10n1pjwvrntsp58s0yxg6szwhfxeg5s3kxvkt9eaaugejtdzpttsef5qwxg06evegspp50udjtr576fjgm3drvt5zhqwax7ap3c4h3ehmwug9cmngdpwy8l9qdq2f38xy6t5wvxqyjw5qcqpxrzjqtypret4hcklglvtfrdt85l3exc0dctdp4qttmtcy5es3lpt6uts6s0yarww0ua5wyqqqqlgqqqqqzsqyg9qxpqysgq76dstp34j9kgtsnsvmwftalxvqt02jdwqxzqjagwaza0f2p4knxkzdhdx6xg3xvte545h4nsd3jayxpjhppca6qrehj7zdad4f25zjsp2ym7y6

**Comment by roeierez** [comment]
Hi @callebtc thanks for reporting that.
When your node doesn't have inbound liquidity and we need to open a channel, we do that in a JIT way during the first incoming payment.
For that to happen we indeed change the node invoice (e.g the payee invoice) before sending it to the sender:
Suppose you want to receive a 50k payment and you use the sdk to create an invoice with 50k.
Behind the scene we subtract the channel opening fee from that invoice (suppose the fee is 2k sats) and create a "lower amount invoice" with 48k sats.
The 50k sats invoice is returned so the payer can pay that amount but the node actually receive 48k sats and from the node perspective the 48k sats invoice is the one that is paid which is why it returns as part of the INVOICE_PAID event.

In your case I see the invoice was not used to open a channel so there shouldn't be a difference, we will take a look into that.
The reason I detailed the above explanation is to note that there will be still cases where the invoice in the event (e.g the node invoice) is different than the payer invoice.
