### ISSUE TITLE
Events for payments in separate instances of the sdk 

### ISSUE THREAD

**Issue by JssDWt** [breez/breez-sdk#657]
Say there's two clients with the same seed. One makes a payment. The one making the payment will receive a `PaymentSucceeded` event in the event listener. The other doesn't.

It could be useful to provide these events in other instances of the sdk as well. So you can have a separate listener in another instance that can do 'work' when payments are made. This listener wants to know about all payments being made. 

The main question is, how to expose this? Do you send events over the current eventlistener on payments from other instances of the sdk too (on sync)? That might give some clutter, since apps would get events for payments they're not interested in. A separate event listener? 

Another option could be an interface that gives you the 'new' payments. Or payments you haven't seen yet, based on a 'last-seen' index.

**Comment by roeierez** [comment]
This can be implemented today by the user by simply routing events from the "instance" listener to a global one (handled by the user).
I am not sure we want to complicate the sdk here given that there is a simple way for the user to implement it.

**Comment by darioAnongba** [comment]
Hi,

This issue came from a question I had for the development team about using the Breez SDK in a backend instead of a user-facing app. The backend uses micro-service architecture. It is still not clear if using the Breez SDK makes sense in this scenario. I will describe it anyways:

## Scenario

Let's say Saylor's company wishes to create a FOSS enabling anyone to deploy their own Lightning Address (if I own `my-domain.com`, I can send an receive bitcoin to `username@my-domain.com`). This FOSS is a simple wrapper around the Breez SDK that supports the [Lightning Address](https://lightningaddress.com/) protocol.

This FOSS is a set of micro-services with a "worker" listener and a "worker" sender.

### Issue 1

Currently, the Breez SDK saves its data using SQLite and persistence operations happen in the background (hidden inside the SDKs methods). This is great for user-facing apps like smartphone wallets or browser extensions where storage is tied to the hardware itself. In the case of the FOSS scenario, what's the impact? Can I run multple "senders" or "listeners" and scale horizontally?

### Issue 2

In the case where the FOSS software generates an invoice to receive payments following the Lightning Address protocol. Will the payment event be received by a listener? Can I run multiple listeners and scale horizontally? If yes, the Breez SDK will update the state upon reception of the payment. If I extended the data by linking this invoice to a specific `username`, how do I manage the extended data and avoid data inconsistencies?

**Comment by darioAnongba** [comment]
Thanks for the quick response. It seems that I misunderstood the storage aspect of the SDK. If it is only internal storage like a cache then it is not an issue.

Regarding the architecture, you are correct that relying on events is not sufficient due to missed events. Your flow seems to be fine as well for this implementation. Maybe websockets will make this a bit easier and actually avoid having to spawn listeners completely? If we imagine 3 MSs that communicate through a message queue:

- an API MS that receive requests, validates data and orchestrates the flow via a message queue
- Sender MSs that send the payments (received from API)
- Listener MSs that listen for invoices (received from API)

It seems that the listeners can be avoided completely if Breez sends a request to a callback upon payment success. So the API MS can:
- On service startup, get all invoices without final status
- Update status by fetching from Breez
- During runtime, expose an endpoint to update a payment as a callback (websocket) for Breez

So this way is more push/sub instead of actively listening to events.

In any case, it seems that the implementation can be done without issues in the current state of the SDK so I think the issue can be closed. Whether by websocket once implemented or today via events.
