### ISSUE TITLE
Better handle swap `last_redeem_error`: "preimage already used"

### ISSUE THREAD

**Issue by ok300** [breez/breez-sdk#710]
A customer reported seeing "preimage already used" in a swap's `last_redeem_error`.

This error message comes from GL, and it's thrown when we try to create an invoice with an already known preimage: https://github.com/ElementsProject/lightning/blob/a59dbbdae5b8f939d378edd18214a591bef79a74/lightningd/invoice.c#L875-L881

If the previous redeem failed, it's unlikely this was the cause. The cause must have happened before, causing us to try to create the invoice again in the next `execute_pending_swaps` attempt.

We should therefore better identify the root cause of this failure and put that in `last_redeem_error`, before we try to re-create the invoice.

**Comment by roeierez** [comment]
Perhaps there are multiple instances involved? Perhaps one instance created the first invoice, then in a second sdk instance (could be restored also) the swapper tries to create the invoice again (since it is not in its db) ?
@ok300  If this is the case one solution is to identify this error and then fetch the invoice from gl instead of creating it.
