### ISSUE TITLE
Support swap-in notifications

### ISSUE THREAD

**Issue by roeierez** [breez/breez-sdk#763]
We want the SDK to register for swap address transactions and notify the user when funds are confirmed.

**Comment by ok300** [comment]
### Swap tx webhook flow


```mermaid
sequenceDiagram
    participant U as User
    participant SDK
    participant N as Chain Notifier
    participant NDS
    participant FCM
    participant D as User Mobile Device

    autonumber
    
    Note over U,SDK: One-time, initial call
    U->>SDK: register_webhook
    
    Note over U: Start swap
    U->>SDK: receive_onchain
    SDK->>N: webhook URL, address
    N->>N: Wait until new tx to address confirms
    N->>NDS: POST (webhook_url, address)
    NDS->>FCM: address_txs_confirmed
    FCM->>D: address_txs_confirmed
```

### Open points

Step 1

- [x] Persist webhook URL

Step 2 / 3

- [ ] Update `receive_onchain` to automatically register for notifications, if `webhook_url` known

Step 4 / 5

- [ ] Update chain notifier to use POST instead of GET

Step 6

- [ ] Rename `AddressTxsChangedPayload` to `AddressTxsConfirmedPayload`, use it as is

Step 7

- [ ] On every received notification, log received payload
