### ISSUE TITLE
Expose top level `drain` method

### ISSUE THREAD

**Issue by rustaceanrob** [breez/breez-sdk#792]
There is a method for the user to `sweep` their LN funds to an on-chain address. A similarly useful function could `drain` the funds to an invoice with an unspecified amount. This method would allow users to smoothly transition between LN wallets without on-chain exposure. Hopefully I'm not missing something, I can work on this if maintainers agree.

**Comment by ok300** [comment]
Thanks for the proposal @rustaceanrob 

This is however trickier than it appears. For example, since it would allow draining to a generic destination, you cannot know for sure what the LN routing fee will be. So you risk leaving some sats behind with this approach.

I will close it, as I don't think this is feasible at the moment.
