### ISSUE TITLE
Add lightning address to payment model

### ISSUE THREAD

**Issue by ademar111190** [breez/breez-sdk#91]
We need to add the lightning address to the payment model https://github.com/breez/breez-sdk/blob/main/libs/sdk-core/src/models.rs#L259-L268 in order to replicate the breez mobile logic here https://github.com/breez/breezmobile/blob/232f1178d86b1b7152a03036ab33aafcf0c933a9/lib/bloc/account/account_model.dart#L885

**Comment by roeierez** [comment]
@ok300 I think we need this to the alpha as well since we are moving now to the sdk input parser in c-breez.
@erdemyerebasmaz but it seems bigger than just adding this data to the pay request, we need to implement the lightning address spec: https://github.com/andrerfneves/lightning-address/blob/master/README.md
Which is a different representation of lnurl pay.

**Comment by ok300** [comment]
The input parser can already decode it:

https://github.com/breez/breez-sdk/blob/e15cb035fe9e7a556aa7cab96cccf2e1fded1bc2/libs/sdk-core/src/input_parser.rs#L219-L256

**Comment by roeierez** [comment]
Right, thanks for the reminder. So just add the address to the payment I guess?

**Comment by ok300** [comment]
Was just looking where is a good place to put it.

How about another optional field in `LnPaymentDetails`?

https://github.com/breez/breez-sdk/blob/e15cb035fe9e7a556aa7cab96cccf2e1fded1bc2/libs/sdk-core/src/models.rs#L293-L304

**Comment by erdemyerebasmaz** [comment]
> Was just looking where is a good place to put it.
> 
> How about another optional field in `LnPaymentDetails`?
> 
> https://github.com/breez/breez-sdk/blob/e15cb035fe9e7a556aa7cab96cccf2e1fded1bc2/libs/sdk-core/src/models.rs#L293-L304

Yes, it should be added to LnPaymentDetails.
